### ISSUE TITLE
Heap sort

### ISSUE THREAD

**Issue by kimia-allami** [kimia-allami/heap-sort#1]
Hi, can someone explain what heap sort is?

**Comment by amirallami-code** [comment]
Hi, Heapsort is a comparison-based sorting algorithm that uses a binary heap data structure. Like mergesort, heapsort has a running time of O , O(n\log n), O(nlogn), and like insertion sort, heapsort sorts in-place, so no extra space is needed during the sort.

**Comment by amirallami-code** [comment]
> Hi, can someone explain what heap sort is?

Heapsort is a comparison-based sorting algorithm that uses a binary heap data structure. Like mergesort, heapsort has a running time of O , O(n\log n), O(nlogn), and like insertion sort, heapsort sorts in-place, so no extra space is needed during the sort.
