### ISSUE TITLE
what is heap sort?

### ISSUE THREAD

**Issue by kimia-allami** [kimia-allami/heap-sort#3]
### Discussed in https://github.com/kimia-allami/heap-sort/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **kimia-allami** August 27, 2024</sup>
hi, can anybody tell me about heap sort? thanks</div>

**Comment by amirallami-code** [comment]
hi, Heap sort is a sorting algorithm that organizes elements in an array to be sorted into a binary heap by repeatedly moving the largest element front he heap and inserting it into the array being sorted. Priority queues are implemented with a heap, a tree-like data structure also used in the heap sort algorithm.
